export default CampaignImages = 
        [{id: 1, image: require("../assets/images/drawn/Campaigns/campaign1.png")},
        {id: 2, image: require("../assets/images/drawn/Campaigns/campaign2.png")},
        {id: 3, image: require("../assets/images/drawn/Campaigns/campaign3.png")},
        {id: 4, image: require("../assets/images/drawn/Campaigns/campaign4.png")},
        {id: 5, image: require("../assets/images/drawn/Campaigns/campaign5.png")},
        {id: 6, image: require("../assets/images/drawn/Campaigns/campaign6.jpg")},
        {id: 7, image: require("../assets/images/drawn/Campaigns/campaign7.png")},
        {id: 8, image: require("../assets/images/drawn/Campaigns/campaign8.jpg")},];